build: false
image: Visual Studio 2017
environment:
    bintray_apikey:
      secure: s+BOuh3hBuWX0CC7gWS+wExeBRmKVO+EcijzMovdqV+95A+O7rMo2D/LnBjxW0IY
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    matrix:
        - CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86
          nodejs_arch: x86
        - CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86
          nodejs_arch: x86
        - CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86_64
          nodejs_arch: x64
        - CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86_64
          nodejs_arch: x64


install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

before_test:
  - ps: Install-Product node 8 $env:nodejs_arch
  - ps: npm install node-gyp -g
  - cmd: node-gyp install

test_script:
  - python build.py

deploy:
  - provider: BinTray
    username: mingyiz
    api_key:
      secure: $env:bintray_apikey
    subject: pluginx
    repo: testing
    package: plugin.node:pluinx
    publish: true
    override: true
    on:
      branch: dev
  - provider: BinTray
    username: mingyiz
    api_key:
      secure: $env:bintray_apikey
    subject: pluginx
    repo: stable
    package: plugin.node:pluinx
    publish: true
    on:
      branch: master
